### PR TITLE
Models, cards, & other related areas

### PR DESCRIPTION
**Pull request by Sajeyks**

### CODE REVIEW

**Comment by Sajeyks** [comment]
Don't merge yet

**Review by FREDERICO23 — APPROVED** [review]
Nice progress...

**Comment by Sajeyks** [comment]
Seems like U resolved the conflicts...

**Review by FREDERICO23 — APPROVED** [review]

**Comment by FREDERICO23** [comment]
I don't really know why these files conflict.
Conflicting files
KenyaDelivers/settings.py
KenyaDelivers/urls.py
README.md
db.sqlite3
service/migrations/0001_initial.py
service/migrations/__pycache__/0001_initial.cpython-37.pyc
service/migrations/__pycache__/__init__.cpython-37.pyc
service/models.py
service/templates/index.html
service/templates/register.html

Try to solve these conflicts

**Pull request closed without merging**
